name = "telegram-psychology-bot"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[env.production]
name = "telegram-psychology-bot"

# Secrets (устанавливаются через wrangler secret put)
# TELEGRAM_BOT_TOKEN
# DATABASE_URL
# OPENAI_API_KEY
# OPENAI_ASSISTANT_ID
